### PR TITLE
fix issue 3083: check user_name claim type

### LINKED ISSUE #3083: Again error from IdP if mapped claim is no string
### What version of UAA are you running?

develop

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew
- using a bosh release I downloaded from bosh.io
- using cf-release
- using cf-deployment
- as part of a commercial Cloud Foundry distribution
- other (please explain)

### What did you do?

Configure external IdP where an array is part of id_token, e.g.

email = [ "one", "two" ]

And email is the user_name. Then we ran into same issue then https://github.com/cloudfoundry/uaa/issues/1831

### What did you expect to see? What goal are you trying to achieve with the UAA?

Either a better error, similar to https://github.com/cloudfoundry/uaa/issues/1831 or a fix like https://github.com/cloudfoundry/uaa/pull/1925

### What did you see instead?

Please include UAA logs if available.

### PR DESCRIPTION
**Pull request by strehle**
solve https://github.com/cloudfoundry/uaa/issues/3083

### CODE REVIEW

**Comment by strehle** [comment]
after first comming

ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')

File: server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java [hunk 1]
```diff
@@ -424,7 +424,7 @@ private String getMappedClaim(String externalName, String internalName, Map<Stri
             return (String) claimObject;
         }
         if (claimObject instanceof Collection) {
-            Set<String> entry = ((Collection<?>) claimObject).stream().map(String.class::cast).collect(Collectors.toSet());
+            Set<String> entry = ((Collection<?>) claimObject).stream().filter(String.class::isInstance).map(String.class::cast).collect(Collectors.toSet());
```
Comment (coolgang123) [inline server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java:427]: Will collection items always going to be a string? Should we consider handle it in more generic way:

Set<String> entry = ((Collection<?>) claimObject).stream()
        .map(claim -> String.valueOf(claim))
        .collect(Collectors.toSet());

Comment (strehle) [reply server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManager.java:427]: I think it is not wanted to have such a generic approach, but simple check if the entries inside of the token are strings. With your approach we allow all but then we are incompatible with now. I mean if claims are type of Boolean or int we would allow them now. But that is not wanted

**Comment by strehle** [comment]
Wanted to solve is that there is a human readable error and not a technical class cast error. The error should show what mapping is wrong, eg. email , first name , user_name etc.

**Review by coolgang123 — APPROVED** [review]

**Review by adrianhoelzl-sap — APPROVED** [review]
