### PR TITLE
Fix issue #1713

### LINKED ISSUE #1713: Missing index for username and identity_zone on users table (Postgres)
### What version of UAA are you running?

75.9.0

### How are you deploying the UAA?

I am deploying the UAA
- locally only using gradlew

### What did you do?

Executed a SQL manually because we had a postgres issue in bigger landscapes

Example:
```
select count(*) from users where ((LOWER(username) = LOWER('marissa') and LOWER(identity_zone_id) = LOWER('uaa')))
```

You may execute explain analyze.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Expected is an indexed scan in the query plan to ensure that we run with the index.

### What did you see instead?

Sequenced scan is done because we have no lower index on idz and origin.

### Reason found in git log

Second query that way adapted in the following commit: https://github.com/cloudfoundry/uaa/commit/dca40d968c42a2b5e09b84639787f9517ecc68b8

### PR DESCRIPTION
**Pull request by torsten-sap**

### CODE REVIEW

File: server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_101_1639764160__Add_LowerIndex_To_Users_Wo_Origin.sql [hunk 1]
```diff
@@ -0,0 +1 @@
+CREATE INDEX concurrently IF NOT EXISTS users_key_lower_wo_origin ON users (LOWER(username),LOWER(identity_zone_id));
```
Comment (strehle) [inline server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_101_1639764160__Add_LowerIndex_To_Users_Wo_Origin.sql]: only one remark, all postgresql relavat commds are in upper case exception concurrently. so you can think about this but no functional change

**Review by strehle — APPROVED** [review]

**Review by strehle — APPROVED** [review]
