### PR TITLE
fix passcode prompt for json responses

### LINKED ISSUE #3314: Does UAA fully support prompt=login according to OIDC specs?
**Description:**
I am using Cloud Foundry UAA as an OpenID Connect (OIDC) identity provider and would like to understand how force authentication is handled in UAA. Specifically, I want to confirm whether the prompt=login parameter in the authorization request enforces re-authentication, even if the user has an active session.

**Steps to Reproduce:**

1. A user logs into an OIDC client application integrated with UAA.
2. The user initiates an authorization request with the following parameters:

     GET /oauth/authorize?
            response_type=code
           &client_id=<client-id>
           &redirect_uri=<redirect-uri>
           &scope=openid
           &prompt=login

3. **Expected behavior:**
        UAA should ignore existing session cookies and force the user to authenticate again.

uaa version which i am using 
UAA Version: 77.10.0

### LINKED ISSUE #3321: 77.27.0 with now prompts for "passcode" when attempting a user login
Using only the internal identity provider, the `/login` json response now includes an extra `passcode` `prompt` compared with 77.26.0.

77.27.0
```
"prompts":{"username":["text","Email"],"password":["password","Password"],"passcode":["password","Temporary Authentication Code ( Get one at https://10.0.16.5:8443/passcode )"]}
```
77.26.0
```
"prompts":{"username":["text","Email"],"password":["password","Password"]}
```

### PR DESCRIPTION
**Pull request by strehle**
See issue #3321

Reverted parts of https://github.com/cloudfoundry/uaa/pull/3254/commits/39490867363b706bd9db4c67401f67d7fc7247eb
But stay with behavior about: do not query always all IdPs

Query the IdP in case it is a default IdP or origin is passed in login hint, means a dedicated IdP is known.

* In these cases check if the IdP has showLoginText = true and **show the prompt.**
* In all other cases - also if no external IdP is configured - **do not show a prompt**

### CODE REVIEW

**Comment by strehle** [comment]
Default before this change

```
curl -s -H"Accept: application/json"  http://localhost:8080/uaa/login |jq
{
  "app": {
    "version": "0.0.0"
  },
  "links": {
    "uaa": "http://localhost:8080/uaa",
    "passwd": "/forgot_password",
    "login": "http://localhost:8080/uaa",
    "register": "/create_account"
  },
  "zone_name": "uaa",
  "entityID": "cloudfoundry-saml-login",
  "commit_id": "0b59fbe",
  "idpDefinitions": {},
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ],
    "passcode": [
      "password",
      "Temporary Authentication Code ( Get one at http://localhost:8080/uaa/passcode )"
    ]
  },
  "timestamp": "2025-03-04T23:58:03+0100"
}
```

**Comment by strehle** [comment]
Default now in UAA with no external IdPs

```
curl -s -H"Accept: application/json"  http://localhost:8080/uaa/login |jq
{
  "app": {
    "version": "0.0.0"
  },
  "links": {
    "uaa": "http://localhost:8080/uaa",
    "passwd": "/forgot_password",
    "login": "http://localhost:8080/uaa",
    "register": "/create_account"
  },
  "zone_name": "uaa",
  "entityID": "cloudfoundry-saml-login",
  "commit_id": "7fc4568",
  "idpDefinitions": {},
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ]
  },
  "timestamp": "2025-03-05T09:50:34+0100"
}
```

**Review by Kehrlann — APPROVED** [review]

File: server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java [hunk 1]
```diff
@@ -652,6 +652,36 @@ private Map<String, SamlIdentityProviderDefinition> getSamlIdentityProviderDefin
...
+        Map<String, AbstractExternalOAuthIdentityProviderDefinition> defaultList = list == null ? new HashMap<>() : list;
+        IdentityProvider oauthIdP = getIdentityProvider(allowedIdps, defaultIdp);
+        if (oauthIdP != null && oauthIdP.getConfig() instanceof AbstractExternalOAuthIdentityProviderDefinition oDefinition) {
+            defaultList.putIfAbsent(oauthIdP.getOriginKey(), oDefinition);
+        }
+        return defaultList;
+    }
+
+    private IdentityProvider getIdentityProvider(List<String> allowedIdps, String defaultIdp) {
+        IdentityProvider samlIdP = null;
```
Comment (adrianhoelzl-sap) [inline server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java]: Is this really always a SAML IdP?

File: server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java [hunk 2]
```diff
@@ -652,6 +652,36 @@ private Map<String, SamlIdentityProviderDefinition> getSamlIdentityProviderDefin
...
+    private Map<String, AbstractExternalOAuthIdentityProviderDefinition> addDefaultOauthMap(Map<String, AbstractExternalOAuthIdentityProviderDefinition> list, List<String> allowedIdps, String defaultIdp) {
+        Map<String, AbstractExternalOAuthIdentityProviderDefinition> defaultList = list == null ? new HashMap<>() : list;
+        IdentityProvider oauthIdP = getIdentityProvider(allowedIdps, defaultIdp);
+        if (oauthIdP != null && oauthIdP.getConfig() instanceof AbstractExternalOAuthIdentityProviderDefinition oDefinition) {
+            defaultList.putIfAbsent(oauthIdP.getOriginKey(), oDefinition);
+        }
+        return defaultList;
+    }
+
+    private IdentityProvider getIdentityProvider(List<String> allowedIdps, String defaultIdp) {
```
Comment (adrianhoelzl-sap) [inline server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java]: Consider renaming the second parameter to `originKey` or something similar

**Review by adrianhoelzl-sap — APPROVED** [review]
