### PR TITLE
2nd alternative fix: allow to change or delete a relyingPartySecret on IdP

### LINKED ISSUE #2880: Cannot remove a secret from IdP via REST
### What version of UAA are you running?

77.8.0 / develop

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

### What did you do?

Create IdP via uaa.yml / but can be done also via REST
https://docs.cloudfoundry.org/api/uaa/version/77.8.0/index.html#oauth-oidc

2nd step. Try to remove the secret, e.g. 
https://docs.cloudfoundry.org/api/uaa/version/77.8.0/index.html#update

### What did you expect to see? What goal are you trying to achieve with the UAA?

Expect that connection to external OIDC IdP is done without secret, e.g. because the other IdP supports public flows.

### What did you see instead?

Secret is used always, because I cannot delete it via REST. Only with access to Database I can remove it.

### PR DESCRIPTION
**Pull request by strehle**
Alternative to PR: https://github.com/cloudfoundry/uaa/pull/2882, https://github.com/cloudfoundry/uaa/pull/2887
and PR: https://github.com/cloudfoundry/uaa/pull/2885

Only one call in backend, but more input on client side.

authMethod is used to make this change non-breakable.
Because before the update prevented the removal of the relyingPartySecret.
No if authMethod is not client_secret_basic or client_secret_post, then the relyingPartySecret can be overwritten with null.

### CODE REVIEW

**Comment by strehle** [comment]
sonar fixes

https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=2896

File: uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java [hunk 1]
```diff
@@ -591,6 +590,7 @@ void createOAuthIdentityProvider() throws Exception {
                 fieldWithPath("config.userInfoUrl").optional(null).type(STRING).description("A URL for fetching user info attributes when queried with the obtained token authorization."),
                 fieldWithPath("config.showLinkText").optional(true).type(BOOLEAN).description("A flag controlling whether a link to this provider's login will be shown on the UAA login page"),
                 fieldWithPath("config.linkText").optional(null).type(STRING).description("Text to use for the login link to the provider"),
+                fieldWithPath("config.auth_method").optional(null).type(STRING).description("<small><mark>UAA 77.10.0</mark></small> Client authentication method. Possible strings are: client_secret_basic, client_secret_post, private_key_jwt, none."),
```
Comment (peterhaochen47) [inline uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java]: Why does this field exist in addition to `config.authMethod` (line 607, currently).

Comment (strehle) [reply uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java]: After diff of the whole code I noticed yes, this is a duplicate. We use authMethod not auth_method.

Removed auth_method

**Review by peterhaochen47 — APPROVED** [review]
