### PR TITLE
fix: support id_token_hint parameter on oidc logout

### LINKED ISSUE #3037: Support id_token_hint external oidc logout
When performing an RP-initiated logout with an external OIDC provider, UAA does not pass the id_token_hint.  This is a required parameter for Okta so single logout does not work with Okta when using OIDC.

### What version of UAA are you running?

v77.10.0

### How are you deploying the UAA?

I am deploying the UAA

- from the git branch

### What did you do?

Configured UAA for external OIDC logins with Okta and enabled RP-initiated logout. Logged in to UAA using the Okta link and then did a logout.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Successful logout at Okta and redirect back to UAA on the post_logout_redirect_uri.

### What did you see instead?

400 Bad Request

### PR DESCRIPTION
**Pull request by mikeroda**
- populate the id_token from an external oidc login into the UAA authentication
- include the id_token in an external oidc logout via the id_token_hint parameter
- fixes #3037

### CODE REVIEW

**Comment by strehle** [comment]
Thanks, I uploaded my draft but will review next days your PR. 
Sonar https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=3049

File: server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaLoginHint.java [hunk 1]
```diff
@@ -32,6 +35,11 @@ public UaaLoginHint(String origin) {
         this.origin = origin;
     }
 
+    public UaaLoginHint(String origin, String idToken) {
```
Comment (strehle) [inline server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaLoginHint.java]: Can you add the id_token_hint to UaaAuthentication or UaaAuthenticationDetails please, see https://github.com/cloudfoundry/uaa/pull/3053 because this class is used to validate the request ... it is used to keep some client informations but it should not contain authentication information

**Review by strehle — DISMISSED** [review]
Please check 'Sonar Test Coverage and please move the id token to object mentioned below...

Please check if the alternative PR https://github.com/cloudfoundry/uaa/pull/3053 would fit to your requirements ...

**Comment by mikeroda** [comment]
> Please check if the alternative PR #3053 would fit to your requirements ...

I pulled down the changes in PR #3053 and tested with Okta and it's working. The changes look good to me, so I we can close this PL and use the alternative PR instead.

File: server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaLoginHint.java (hunk 1 above)
Comment (mikeroda) [reply server/src/main/java/org/cloudfoundry/identity/uaa/authentication/UaaLoginHint.java]: OK I added the id_token_hint to the UaaAuthentication. New commit is shown below.

**Comment by strehle** [comment]
The only open task for this PR would be sonar: https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=3049 and test coverage > 80

**Review by strehle — COMMENTED** [review]
please add Unit Tests for new code
https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=3049

File: server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerTest.java [hunk 2]
```diff
@@ -5,6 +5,9 @@
 import com.nimbusds.jose.JOSEException;
 import com.nimbusds.jose.JWSAlgorithm;
 import com.nimbusds.jose.JWSSigner;
+
```
Comment (strehle) [inline server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerTest.java]:
```suggestion
```

Comment (strehle) [reply server/src/test/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthAuthenticationManagerTest.java]: unused

File: server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthLogoutHandler.java [hunk 3]
```diff
@@ -1,6 +1,8 @@
 package org.cloudfoundry.identity.uaa.provider.oauth;
 
 import org.cloudfoundry.identity.uaa.authentication.UaaAuthentication;
+import org.cloudfoundry.identity.uaa.authentication.UaaAuthenticationDetails;
```
Comment (strehle) [inline server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthLogoutHandler.java]:
```suggestion
```

File: server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthLogoutHandler.java [hunk 4]
```diff
@@ -1,6 +1,8 @@
...
+import org.cloudfoundry.identity.uaa.authentication.UaaLoginHint;
```
Comment (strehle) [inline server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/ExternalOAuthLogoutHandler.java]:
```suggestion
```

**Review by strehle — APPROVED** [review]
Some sonar cleanup, but OK

**Review by peterhaochen47 — APPROVED** [review]

**Comment by peterhaochen47** [comment]
@strehle Feel free to merge
