### PR TITLE
Fix regression in identity-provider endpoint

### LINKED ISSUE #2963: Regression in Identity-Provider Endpoint
### What version of UAA are you running?

UAA 77.13.0 with existing OIDC Idps. Call them via REST

uaac curl -X PUT /identity-providers/3ad529ed-3ef0-498d-b79e-9a6b0512ce8c

issuer is null

Reason: 
If no external id is set, then issuer is overwritten with null
https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java#L215

### How are you deploying the UAA?

- locally only using gradlew
- using a bosh release I downloaded from bosh.io
- using cf-release
- using cf-deployment

### What did you do?

uaac curl -X PUT /identity-providers/3ad529ed-3ef0-498d-b79e-9a6b0512ce8c

### What did you expect to see? What goal are you trying to achieve with the UAA?

issuer of OIDC IdP

### What did you see instead?

issuer null

Please include UAA logs if available.

### PR DESCRIPTION
**Pull request by strehle**
Issue:
If existing entries in identity-provider with new external_key the field is null, which is expected. If external_key is null, this must not overwrite the issuer in rest endpoint, but it does

For SAML there is no issue, because here the entityId is really new in REST output and in DB. For OIDC and OAuth2 the issuer was used in REST already and there was no check before overwrite it from external_key.

### CODE REVIEW

File: server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java [hunk 1]
```diff
@@ -218,15 +219,21 @@ public IdentityProvider mapRow(ResultSet rs, int rowNum) throws SQLException {
                 switch (identityProvider.getType()) {
                     case OriginKeys.SAML:
                         definition = JsonUtils.readValue(config, SamlIdentityProviderDefinition.class);
-                        Optional.ofNullable(definition).map(SamlIdentityProviderDefinition.class::cast).ifPresent(e -> e.setIdpEntityId(externId));
+                        if (isNotEmpty(externId)) {
```
Comment (adrianhoelzl-sap) [inline server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java]: Can we rename `externId` to `externalKey` to be consistent with the column name?

File: server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java [hunk 2]
```diff
@@ -218,15 +219,21 @@ public IdentityProvider mapRow(ResultSet rs, int rowNum) throws SQLException {
...
+                            Optional.ofNullable(definition).map(SamlIdentityProviderDefinition.class::cast).ifPresent(e -> e.setIdpEntityId(externId));
```
Comment (adrianhoelzl-sap) [inline server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java]: Instead of the surrounding `if` statement, we could also use `.filter(UaaStringUtils::isNotEmpty)` before the call to `ifPresent`.

For me, both is fine.

File: server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java (hunk 1 above)
Comment (strehle) [reply server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java]: done

File: server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java (hunk 2 above)
Comment (strehle) [reply server/src/main/java/org/cloudfoundry/identity/uaa/provider/JdbcIdentityProviderProvisioning.java]: no this is not working since the externalKey is not part of the config JSON....

**Comment by strehle** [comment]
Sonar

https://sonarcloud.io/summary/new_code?id=cloudfoundry-identity-parent&pullRequest=2962

**Review by adrianhoelzl-sap — APPROVED** [review]
